from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
import os

def add_run_with_style(para, text, bold=False, size=11, color=None):
    run = para.add_run(text)
    run.bold = bold
    run.font.size = Pt(size)
    if color:
        run.font.color.rgb = RGBColor(*color)
    return run

def generate_question_bank_docx(data, output_path):
    doc = Document()
    
    # Margins
    for section in doc.sections:
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)
        section.top_margin = Inches(0.8)
        section.bottom_margin = Inches(0.8)

    # Header
    title_para = doc.add_paragraph()
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subject_name = data.get('subject_name', 'Subject Name').upper()
    add_run_with_style(title_para, subject_name, bold=True, size=16, color=(11, 87, 208))
    
    subtitle_para = doc.add_paragraph()
    subtitle_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    add_run_with_style(subtitle_para, 'QUESTION BANK', bold=True, size=12, color=(100, 100, 100))
    
    doc.add_paragraph() # spacer

    for module in data.get('modules', []):
        # Module Header
        mod_para = doc.add_paragraph()
        mod_para.alignment = WD_ALIGN_PARAGRAPH.LEFT
        add_run_with_style(mod_para, module['name'], bold=True, size=13)
        
        # Add a light bottom border to the module header (using horizontal rule logic)
        from docx.oxml.ns import qn
        from docx.oxml import OxmlElement
        pPr = mod_para._p.get_or_add_pPr()
        pBdr = OxmlElement('w:pBdr')
        bottom = OxmlElement('w:bottom')
        bottom.set(qn('w:val'), 'single')
        bottom.set(qn('w:sz'), '4')
        bottom.set(qn('w:space'), '1')
        bottom.set(qn('w:color'), 'E3E2E6')
        pBdr.append(bottom)
        pPr.append(pBdr)

        # Questions
        for i, question in enumerate(module.get('questions', []), 1):
            q_para = doc.add_paragraph(style='List Number')
            add_run_with_style(q_para, question, size=11)
        
        doc.add_paragraph() # spacing between modules

    # Footer instructions
    footer_para = doc.add_paragraph()
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    add_run_with_style(footer_para, "\nGenerated by TutorVision AI", size=9, color=(128, 128, 128))

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    doc.save(output_path)
    return output_path
