from fpdf import FPDF
import os

from .pdf_generator import sanitize_pdf_text

class QB_PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.set_text_color(11, 87, 208) # Professional Blue
        self.cell(0, 10, self.subject_title, 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 5, 'QUESTION BANK', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Generated by TutorVision AI - Page {self.page_no()}', 0, 0, 'C')

def generate_question_bank_pdf(data, output_path):
    pdf = QB_PDF()
    pdf.subject_title = sanitize_pdf_text(data.get('subject_name', 'Subject Name')).upper()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    for module in data.get('modules', []):
        # Module Header
        pdf.set_font('Arial', 'B', 12)
        pdf.set_fill_color(240, 244, 249)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, f" {sanitize_pdf_text(module['name'])}", 0, 1, 'L', fill=True)
        pdf.ln(2)
        
        # Questions
        pdf.set_font('Arial', '', 11)
        for i, question in enumerate(module.get('questions', []), 1):
            # SAFETY CHECK: If we are near the bottom (~25mm), start a new page
            # This prevents the number appearing on one page and text on the next
            if pdf.get_y() > 260:
                pdf.add_page()

            # Handle long questions with multi_cell
            pdf.set_x(15)
            # Bullet point
            current_y = pdf.get_y()
            pdf.set_font('Arial', 'B', 11)
            pdf.text(10, current_y + 4, f"{i}. ")
            pdf.set_font('Arial', '', 11)
            pdf.multi_cell(0, 6, sanitize_pdf_text(question), 0, 'L')
            pdf.ln(3)
        
        pdf.ln(5)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    pdf.output(output_path)
    return output_path
